// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://thkicxiyzslbndjtdcoy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRoa2ljeGl5enNsYm5kanRkY295Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg3MjgzNjIsImV4cCI6MjA1NDMwNDM2Mn0.LYyqKHIadLrnBWbsDyr6v-74o7IyYNgYYkMXotr4nl8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);